### ISSUE TITLE
Introduce changelog and version tagging

### ISSUE THREAD

**Issue by eshepelyuk** [sonatype-nexus-community/helm-nexus-push#10]
Hello

It would be great to introduce release procedure so there will be changelogs and release tags.
It would help to install particular version of plugin and not rely on master, that could be broken, for instance.

If interested I can describe, implement approach I'm using in my GitHub projects suing conventional commit and [release-it tool](https://www.npmjs.com/package/release-it)

**Comment by dtshepherd** [comment]
Sure, I’m all for better release procedures!  I just don’t have much time to invest in this plugin given my other workload right now.

**Comment by eshepelyuk** [comment]
So I'll try to make PR then. Using tools and approaches I've described.
